/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all dogs for authenticated user
         * @description Retrieves all dogs owned by the authenticated user.
         *     Uses DynamoDB GSI (owner-index) for efficient querying.
         */
        get: operations["listDogs"];
        put?: never;
        /**
         * Register a new dog
         * @description Creates a new dog profile linked to the authenticated user.
         *     Validates that owner profile exists before allowing dog registration.
         *     Automatically calculates age from date of birth.
         */
        post: operations["createDog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dogs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dog by ID
         * @description Retrieves a specific dog by ID with owner verification.
         *     Returns 403 if the dog doesn't belong to the authenticated user.
         */
        get: operations["getDog"];
        /**
         * Update dog information
         * @description Updates an existing dog's information with owner verification.
         *     Only allows updating specific fields; owner_id cannot be changed.
         */
        put: operations["updateDog"];
        post?: never;
        /**
         * Delete dog
         * @description Deletes a dog profile with owner verification.
         *     Returns 204 No Content on success.
         */
        delete: operations["deleteDog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owners/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get owner profile
         * @description Retrieves the authenticated user's profile (preferences only, no PII).
         *     Auto-creates a basic profile if none exists.
         */
        get: operations["getOwnerProfile"];
        /**
         * Update owner profile
         * @description Updates owner preferences and notification settings.
         *     No PII is stored; all identity information comes from Firebase JWT.
         */
        put: operations["updateOwnerProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owners/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new owner profile
         * @description Creates initial owner profile for a new user.
         *     Requires email verification via Firebase.
         *     Returns 400 if profile already exists.
         */
        post: operations["registerOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all bookings for authenticated user
         * @description Retrieves all bookings for the authenticated user.
         *     Results are sorted by start_time in descending order.
         */
        get: operations["listBookings"];
        put?: never;
        /**
         * Create a new booking
         * @description Creates a new service booking with automatic slot capacity reservation.
         *     Validates dog ownership, venue existence, and slot availability.
         *     Atomically reserves slot capacity; rolls back on failure.
         *     Calculates price based on service type and duration.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get booking by ID
         * @description Retrieves a specific booking by ID
         */
        get: operations["getBooking"];
        /**
         * Update booking
         * @description Updates an existing booking.
         *     Note: Changing times does not currently re-check slot availability.
         */
        put: operations["updateBooking"];
        post?: never;
        /**
         * Cancel booking
         * @description Cancels a booking and releases slot capacity.
         *     Sets status to 'cancelled' rather than deleting the record.
         */
        delete: operations["cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all venues
         * @description Retrieves all venues (public endpoint for browsing).
         *     Supports optional limit parameter for pagination.
         */
        get: operations["listVenues"];
        put?: never;
        /**
         * Create a new venue
         * @description Creates a new venue and auto-generates slots for the next 30 days.
         *     Requires valid operating hours for all open days.
         */
        post: operations["createVenue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get venue by ID
         * @description Retrieves detailed information about a specific venue
         */
        get: operations["getVenue"];
        /**
         * Update venue
         * @description Updates venue information.
         *     Note: Changing capacity or operating hours does not update existing slots.
         */
        put: operations["updateVenue"];
        post?: never;
        /**
         * Delete venue
         * @description Deletes a venue.
         *     Warning: Does not cascade delete slots or bookings.
         */
        delete: operations["deleteVenue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/batch-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch generate slots for a venue
         * @description Generates time slots for a venue across a date range.
         *     Slots are created based on venue operating hours and capacity.
         *     Uses DynamoDB batch writes for efficiency (25 items per batch).
         */
        post: operations["batchGenerateSlots"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query slot availability across venues
         * @description Retrieves available slots for all venues on a specific date.
         *     Uses DynamoDB GSI (date-venue-index) for efficient querying.
         *     Only returns slots with available capacity > 0.
         */
        get: operations["queryAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/venue/{venue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get slots for a specific venue in a date range
         * @description Retrieves all slots for a venue within a date range.
         *     If end_date is not provided, defaults to start_date (single day).
         */
        get: operations["getVenueSlotsRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API documentation UI
         * @description Serves interactive API documentation (Swagger UI)
         */
        get: operations["getDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI specification
         * @description Returns the OpenAPI specification in JSON format
         */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Dog size classification
         * @enum {string}
         */
        DogSize: "SMALL" | "MEDIUM" | "LARGE" | "XLARGE";
        /**
         * @description Dog vaccination status
         * @enum {string}
         */
        VaccinationStatus: "VACCINATED" | "NOT_VACCINATED";
        DogRequest: {
            /**
             * @description Dog's name
             * @example Max
             */
            name: string;
            /**
             * @description Dog breed
             * @example Golden Retriever
             */
            breed: string;
            /**
             * Format: date
             * @description Dog's date of birth (ISO 8601 format, cannot be in the future)
             * @example 2020-05-15
             */
            date_of_birth: string;
            size: components["schemas"]["DogSize"];
            vaccination_status: components["schemas"]["VaccinationStatus"];
            /**
             * @description Whether the dog is microchipped
             * @default false
             */
            microchipped: boolean;
            /**
             * @description List of special needs or requirements
             * @default []
             * @example [
             *       "separation anxiety",
             *       "food allergies"
             *     ]
             */
            special_needs: string[];
            /**
             * @description Medical history and notes
             * @default
             * @example Allergic to chicken
             */
            medical_notes: string;
            /**
             * @description Behavioral observations and notes
             * @default
             * @example Friendly with other dogs
             */
            behavior_notes: string;
            /**
             * @description Preferred activities
             * @default
             * @example Fetch, swimming
             */
            favorite_activities: string;
        };
        DogResponse: {
            /**
             * @description Unique dog identifier
             * @example dog-123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /** @example Max */
            name: string;
            /** @example Golden Retriever */
            breed: string;
            /**
             * Format: date
             * @example 2020-05-15
             */
            date_of_birth: string;
            /**
             * @description Calculated age from date of birth
             * @example 4 years, 3 months
             */
            age: string;
            size: components["schemas"]["DogSize"];
            vaccination_status: components["schemas"]["VaccinationStatus"];
            microchipped?: boolean;
            special_needs?: string[];
            medical_notes?: string;
            behavior_notes?: string;
            favorite_activities?: string;
            /**
             * @description Firebase user ID of the owner
             * @example firebase-user-123
             */
            owner_id: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            updated_at: string;
        };
        DogListResponse: {
            dogs: components["schemas"]["DogResponse"][];
            /**
             * @description Number of dogs returned
             * @example 3
             */
            count: number;
        };
        OwnerPreferences: {
            /**
             * @description Enable push notifications
             * @default true
             */
            notifications: boolean;
            /**
             * @description Receive marketing communications
             * @default false
             */
            marketing_emails: boolean;
            /**
             * @default email
             * @enum {string}
             */
            preferred_communication: "email" | "sms" | "push";
        };
        OwnerProfileRequest: {
            preferences?: components["schemas"]["OwnerPreferences"];
            /** @description Granular notification settings */
            notification_settings?: {
                [key: string]: unknown;
            };
        };
        OwnerProfileResponse: {
            /**
             * @description Firebase user ID (not PII)
             * @example firebase-user-123
             */
            user_id: string;
            preferences: components["schemas"]["OwnerPreferences"];
            notification_settings?: {
                [key: string]: unknown;
            };
            /**
             * @description Whether profile setup is complete
             * @example true
             */
            registration_complete?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Type of service being booked
         * @enum {string}
         */
        ServiceType: "daycare" | "boarding" | "grooming" | "walking" | "training";
        /**
         * @description Current status of the booking
         * @enum {string}
         */
        BookingStatus: "pending" | "confirmed" | "in_progress" | "completed" | "cancelled";
        BookingRequest: {
            /**
             * @description ID of the dog being booked
             * @example dog-123e4567-e89b-12d3-a456-426614174000
             */
            dog_id: string;
            /**
             * @description ID of the venue
             * @example venue-123e4567-e89b-12d3-a456-426614174000
             */
            venue_id: string;
            service_type: components["schemas"]["ServiceType"];
            /**
             * Format: date-time
             * @description Booking start time (ISO 8601)
             * @example 2024-01-20T09:00:00Z
             */
            start_time: string;
            /**
             * Format: date-time
             * @description Booking end time (ISO 8601, must be after start_time)
             * @example 2024-01-20T17:00:00Z
             */
            end_time: string;
            /**
             * @description Special instructions for the booking
             * @default
             * @example Please use the special harness
             */
            special_instructions: string;
        };
        BookingResponse: {
            /** @example booking-123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            dog_id: string;
            owner_id: string;
            venue_id: string;
            service_type: components["schemas"]["ServiceType"];
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            status: components["schemas"]["BookingStatus"];
            /**
             * Format: float
             * @description Price in GBP calculated from service type and duration
             * @example 120
             */
            price: number;
            special_instructions?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BookingListResponse: {
            bookings: components["schemas"]["BookingResponse"][];
            /** @example 5 */
            count: number;
        };
        BookingUpdateRequest: {
            service_type?: components["schemas"]["ServiceType"];
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            status?: components["schemas"]["BookingStatus"];
            special_instructions?: string;
        };
        /** @description Operating hours for each day of the week */
        OperatingHours: {
            monday?: components["schemas"]["DayHours"];
            tuesday?: components["schemas"]["DayHours"];
            wednesday?: components["schemas"]["DayHours"];
            thursday?: components["schemas"]["DayHours"];
            friday?: components["schemas"]["DayHours"];
            saturday?: components["schemas"]["DayHours"];
            sunday?: components["schemas"]["DayHours"];
        };
        DayHours: {
            /**
             * @description Whether the venue is open on this day
             * @default true
             */
            open: boolean;
            /**
             * @description Opening time in HH:MM format (24-hour)
             * @example 09:00
             */
            start?: string;
            /**
             * @description Closing time in HH:MM format (24-hour)
             * @example 18:00
             */
            end?: string;
        };
        VenueRequest: {
            /**
             * @description Venue name
             * @example Happy Paws Downtown
             */
            name: string;
            /**
             * @description Full venue address
             * @example 123 Main St, London, UK
             */
            address: string;
            /**
             * Format: float
             * @description Latitude coordinate (WGS84)
             * @example 51.5074
             */
            latitude: number;
            /**
             * Format: float
             * @description Longitude coordinate (WGS84)
             * @example -0.1278
             */
            longitude: number;
            /**
             * @description Maximum number of dogs that can be accommodated simultaneously
             * @example 20
             */
            capacity: number;
            operating_hours: components["schemas"]["OperatingHours"];
            /**
             * @description Services offered at this venue
             * @default [
             *       "daycare"
             *     ]
             */
            services: components["schemas"]["ServiceType"][];
            /**
             * @description Duration of each time slot in minutes
             * @default 60
             */
            slot_duration: number;
        };
        VenueResponse: {
            /** @example venue-123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            name: string;
            address: string;
            /**
             * Format: float
             * @description Latitude coordinate (WGS84)
             * @example 51.5074
             */
            latitude: number;
            /**
             * Format: float
             * @description Longitude coordinate (WGS84)
             * @example -0.1278
             */
            longitude: number;
            capacity: number;
            operating_hours: components["schemas"]["OperatingHours"];
            services?: components["schemas"]["ServiceType"][];
            slot_duration?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        VenueListResponse: {
            venues: components["schemas"]["VenueResponse"][];
            /** @example 10 */
            count: number;
        };
        SlotBatchGenerateRequest: {
            /**
             * @description Venue ID to generate slots for
             * @example venue-123e4567-e89b-12d3-a456-426614174000
             */
            venue_id: string;
            /**
             * Format: date
             * @description Start date for slot generation (YYYY-MM-DD)
             * @example 2024-01-01
             */
            start_date: string;
            /**
             * Format: date
             * @description End date for slot generation (YYYY-MM-DD, must be >= start_date)
             * @example 2024-01-31
             */
            end_date: string;
        };
        SlotBatchGenerateResponse: {
            /** @example Slots generated successfully */
            message: string;
            venue_id: string;
            date_range: {
                /** Format: date */
                start?: string;
                /** Format: date */
                end?: string;
            };
            /**
             * @description Total number of slots created
             * @example 240
             */
            slots_created: number;
        };
        SlotAvailability: {
            /**
             * @description Time slot in HH:MM format
             * @example 09:00
             */
            time: string;
            /**
             * @description Available capacity for this slot
             * @example 15
             */
            available: number;
            /**
             * @description Total capacity for this slot
             * @example 20
             */
            total: number;
        };
        SlotAvailabilityResponse: {
            /** Format: date */
            date: string;
            /** @description Map of venue IDs to their available slots */
            venues_with_availability: {
                [key: string]: components["schemas"]["SlotAvailability"][];
            };
            /**
             * @description Number of venues with availability
             * @example 3
             */
            total_venues: number;
        };
        VenueSlotsResponse: {
            venue_id: string;
            date_range: {
                /** Format: date */
                start?: string;
                /** Format: date */
                end?: string;
            };
            /** @description Map of dates to slot arrays */
            slots: {
                [key: string]: {
                    venue_date?: string;
                    slot_time?: string;
                    venue_id?: string;
                    date?: string;
                    available_capacity?: number;
                    total_capacity?: number;
                    booked_count?: number;
                    /** Format: date-time */
                    created_at?: string;
                }[];
            };
        };
        ErrorResponse: {
            /**
             * @description Human-readable error message
             * @example Dog not found
             */
            error: string;
        };
        ValidationErrorResponse: {
            errors: {
                /** @description Location of the error in the request */
                loc?: string[];
                /** @description Error message */
                msg?: string;
                /** @description Error type */
                type?: string;
            }[];
        };
        MessageResponse: {
            /** @example Operation successful */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of dogs retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogListResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createDog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DogRequest"];
            };
        };
        responses: {
            /** @description Dog created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogResponse"];
                };
            };
            /** @description Invalid request data or owner profile not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Dog ID
                 * @example dog-123e4567-e89b-12d3-a456-426614174000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dog retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied - not your dog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dog not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateDog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dog ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    breed?: string;
                    age?: string;
                    size?: components["schemas"]["DogSize"];
                    vaccination_status?: components["schemas"]["VaccinationStatus"];
                    special_needs?: string[];
                    medical_notes?: string;
                    behavior_notes?: string;
                    favorite_activities?: string;
                    microchipped?: boolean;
                };
            };
        };
        responses: {
            /** @description Dog updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogResponse"];
                };
            };
            /** @description Invalid JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied - not your dog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dog not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dog ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dog deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied - not your dog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dog not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOwnerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerProfileResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateOwnerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerProfileRequest"];
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerProfileResponse"];
                };
            };
            /** @description Invalid JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerProfileRequest"];
            };
        };
        responses: {
            /** @description Profile created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Profile created successfully */
                        message?: string;
                        user_id?: string;
                        preferences?: components["schemas"]["OwnerPreferences"];
                    };
                };
            };
            /** @description Invalid request or profile already exists */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description Booking created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Invalid request data or no availability */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dog does not belong to this owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dog, venue, or owner not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error or capacity reservation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingUpdateRequest"];
            };
        };
        responses: {
            /** @description Booking updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Invalid JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listVenues: {
        parameters: {
            query?: {
                /** @description Maximum number of venues to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Venues retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueListResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createVenue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            /** @description Venue created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Venue ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Venue retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueResponse"];
                };
            };
            /** @description Venue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateVenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Venue ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    address?: string;
                    /** Format: float */
                    latitude?: number;
                    /** Format: float */
                    longitude?: number;
                    capacity?: number;
                    operating_hours?: components["schemas"]["OperatingHours"];
                    services?: components["schemas"]["ServiceType"][];
                    slot_duration?: number;
                };
            };
        };
        responses: {
            /** @description Venue updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Venue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteVenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Venue ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Venue deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Venue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    batchGenerateSlots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotBatchGenerateRequest"];
            };
        };
        responses: {
            /** @description Slots generated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotBatchGenerateResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Venue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    queryAvailability: {
        parameters: {
            query: {
                /**
                 * @description Date to query availability for (YYYY-MM-DD)
                 * @example 2024-01-20
                 */
                date: string;
                /** @description Filter by service type (currently informational only) */
                service_type?: components["schemas"]["ServiceType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotAvailabilityResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVenueSlotsRange: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                start_date: string;
                /** @description End date (YYYY-MM-DD), defaults to start_date if not provided */
                end_date?: string;
            };
            header?: never;
            path: {
                /** @description Venue ID */
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slots retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueSlotsResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML documentation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
